# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: valveextensions.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'valveextensions.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import descriptor_pb2 as google_dot_protobuf_dot_descriptor__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15valveextensions.proto\x1a google/protobuf/descriptor.proto:?\n\x0fvalve_map_field\x12\x1d.google.protobuf.FieldOptions\x18\xc8\xdc\x03 \x01(\x08:\x05\x66\x61lse:=\n\rvalve_map_key\x12\x1d.google.protobuf.FieldOptions\x18\xc9\xdc\x03 \x01(\x08:\x05\x66\x61lse:=\n\x11\x64iff_encode_field\x12\x1d.google.protobuf.FieldOptions\x18\xca\xdc\x03 \x01(\x05:\x01\x30:<\n\x0c\x64\x65lta_ignore\x12\x1d.google.protobuf.FieldOptions\x18\xcb\xdc\x03 \x01(\x08:\x05\x66\x61lse:?\n\x13steamml_max_entries\x12\x1d.google.protobuf.FieldOptions\x18\xcc\xdc\x03 \x01(\r:\x01\x30:D\n\x14steamml_is_timestamp\x12\x1d.google.protobuf.FieldOptions\x18\xcd\xdc\x03 \x01(\x08:\x05\x66\x61lse:<\n\x10steamlearn_count\x12\x1d.google.protobuf.FieldOptions\x18\xce\xdc\x03 \x01(\r:\x01\x30:@\n\x14schema_friendly_name\x12!.google.protobuf.EnumValueOptions\x18\xe8\x07 \x01(\t:>\n\x12schema_description\x12!.google.protobuf.EnumValueOptions\x18\xe9\x07 \x01(\t:F\n\x1aschema_suppress_enumerator\x12!.google.protobuf.EnumValueOptions\x18\xea\x07 \x01(\x08')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'valveextensions_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
# @@protoc_insertion_point(module_scope)
